### ISSUE TITLE
npm WARN for fsevents 

### ISSUE THREAD

**Issue by forconz** [siteserver/cms#1739]
PS D:\Projects\Tendbot\docs\src> npm install gulp -g
C:\Users\Tao\AppData\Roaming\npm\gulp -> C:\Users\Tao\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\gulp\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ gulp@4.0.0
added 318 packages from 218 contributors in 42.544s

这个警告信息是在windows下产生的，fsevents 是mac下的库，这个警告能消除吗？

**Comment by forconz** [comment]
PS D:\Projects\Tendbot\docs\src> npm install
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated gulp-util@2.2.20: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN siteserver@1.0.0 No repository field.

added 457 packages from 224 contributors and audited 1720 packages in 11.467s
**found 8 vulnerabilities (3 low, 5 high)**
  run `npm audit fix` to fix them, or `npm audit` for details

**Comment by forconz** [comment]
gulp build出错了

PS D:\Projects\docs\src> gulp build
[09:19:59] Using gulpfile D:\Projects\docs\src\gulpfile.js
[09:19:59] Starting 'build'...
build version: 0.0.0
[09:19:59] Starting 'build-docs'...
[09:19:59] Finished 'build-docs' after 30 ms
[09:19:59] Starting 'build-webconfig'...
[09:19:59] Finished 'build-webconfig' after 5.26 ms
[09:19:59] Starting 'build-nuspec'...
[09:19:59] 'build-nuspec' errored after 225 μs
[09:19:59] Error: ENOENT: no such file or directory, scandir 'D:\Projects\docs\src\packages'
    at Object.fs.readdirSync (fs.js:921:18)
    at getDependencies (D:\Projects\docs\src\gulpfile.js:18:17)
    at Gulp.<anonymous> (D:\Projects\docs\src\gulpfile.js:40:22)
    at module.exports (D:\Projects\docs\src\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (D:\Projects\docs\src\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (D:\Projects\docs\src\node_modules\orchestrator\index.js:214:10)
    at Gulp.Orchestrator.start (D:\Projects\docs\src\node_modules\orchestrator\index.js:134:8)
    at runNextSet (D:\Projects\docs\src\node_modules\run-sequence\index.js:124:15)
    at Gulp.onTaskEnd (D:\Projects\docs\src\node_modules\run-sequence\index.js:102:4)
    at Gulp.emit (events.js:185:15)
[09:19:59] Error in plugin "run-sequence(build-nuspec)"
Message:
    ENOENT: no such file or directory, scandir 'D:\Projects\docs\src\packages'
Details:
    errno: -4058
    code: ENOENT
    syscall: scandir
    path: D:\Projects\docs\src\packages

Stack:
Error: ENOENT: no such file or directory, scandir 'D:\Projects\docs\src\packages'
    at Object.fs.readdirSync (fs.js:921:18)
    at getDependencies (D:\Projects\docs\src\gulpfile.js:18:17)
    at Gulp.<anonymous> (D:\Projects\docs\src\gulpfile.js:40:22)
    at module.exports (D:\Projects\docs\src\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (D:\Projects\docs\src\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (D:\Projects\docs\src\node_modules\orchestrator\index.js:214:10)
    at Gulp.Orchestrator.start (D:\Projects\docs\src\node_modules\orchestrator\index.js:134:8)
    at runNextSet (D:\Projects\docs\src\node_modules\run-sequence\index.js:124:15)
    at Gulp.onTaskEnd (D:\Projects\docs\src\node_modules\run-sequence\index.js:102:4)
    at Gulp.emit (events.js:185:15)

**Comment by XiaoLiu-Lin** [comment]
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.8 (node_modules\fsevents):
