### ISSUE TITLE
gulp build 报错

### ISSUE THREAD

**Issue by jesonwong** [siteserver/cms#1894]
fs.js:27
const { Math, Object, Reflect } = primordials;
                                  ^

ReferenceError: primordials is not defined
    at fs.js:27:35
    at req_ (D:\project\github\cms\node_modules\natives\index.js:143:24)
    at Object.req [as require] (D:\project\github\cms\node_modules\natives\index.js:55:10)
    at Object.<anonymous> (D:\project\github\cms\node_modules\graceful-fs\fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)

**Comment by jesonwong** [comment]
staging v6.10.1
SiteServer.Cli中的nuget包都更新到最新版本，打包编译报上面的错误，帮忙看看什么问题导致的

**Comment by lqdcanty** [comment]
请问你解决问题了嘛？问也越到了同样的问题

**Comment by dgtg77** [comment]
同样的错，怎么解决的
