### ISSUE TITLE
gulp build 时报，TypeError: gulp.hasTask is not a function 错误

### ISSUE THREAD

**Issue by challengesoflife** [siteserver/cms#2045]
使用gulp build打包时报TypeError: gulp.hasTask is not a function 错误

`E:\studyfile\visualstudio.com\siteCMS\cms-master>gulp build
[21:22:22] Using gulpfile E:\studyfile\visualstudio.com\siteCMS\cms-master\gulpf
ile.js
[21:22:22] Starting 'build'...
build version: 0.0.0
[21:22:22] 'build' errored after 5.53 ms
[21:22:22] TypeError: gulp.hasTask is not a function
    at E:\studyfile\visualstudio.com\siteCMS\cms-master\node_modules\run-sequenc
e\index.js:23:22
    at Array.forEach (<anonymous>)
    at verifyTaskSets (E:\studyfile\visualstudio.com\siteCMS\cms-master\node_mod
ules\run-sequence\index.js:17:11)
    at runSequence (E:\studyfile\visualstudio.com\siteCMS\cms-master\node_module
s\run-sequence\index.js:130:2)
    at E:\studyfile\visualstudio.com\siteCMS\cms-master\gulpfile.js:172:3
    at taskWrapper (E:\studyfile\visualstudio.com\siteCMS\cms-master\node_module
s\undertaker\lib\set-task.js:13:15)
    at bound (domain.js:402:14)
    at runBound (domain.js:415:12)
    at asyncRunner (E:\studyfile\visualstudio.com\siteCMS\cms-master\node_module
s\async-done\index.js:55:18)
    at process._tickCallback (internal/process/next_tick.js:61:11)

E:\studyfile\visualstudio.com\siteCMS\cms-master>`

**Comment by challengesoflife** [comment]
问题已解决：
原因是本地的gulp 的本为4.0导致的。
出错时gulp 的版本如下：
![image](https://user-images.githubusercontent.com/33093653/62630761-27f7de00-b962-11e9-85c9-f11dee7aeaef.png)

将gulp 的版本降级为gulp 3.9,版本降级之后为：
![image](https://user-images.githubusercontent.com/33093653/62630835-4362e900-b962-11e9-972c-c2158f77cddd.png)

完了，再运行 gulp build 就OK了。
