### ISSUE TITLE
初始化后管理员创建失败，数据库里查不到管理员信息

### ISSUE THREAD

**Issue by Eric-zsp** [siteserver/cms#2572]
**### docker运行，连接宿主的mysql数据库。具体报错如下**
2020-09-16 13:12:18.948 +00:00 [WRN] Storing keys in a directory '/root/.aspnet/DataProtection-Keys' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed.
2020-09-16 13:12:18.984 +00:00 [INF] User profile is available. Using '/root/.aspnet/DataProtection-Keys' as key repository; keys will not be encrypted at rest.
2020-09-16 13:12:19.000 +00:00 [INF] Creating key "1559bdc7-e836-4b32-9c58-03185d2e0cb2" with creation date "2020-09-16T13:12:18.9969224+00:00", activation date "2020-09-16T13:12:18.9930173+00:00", and expiration date "2020-12-15T13:12:18.9930173+00:00".
2020-09-16 13:12:19.016 +00:00 [WRN] No XML encryptor configured. Key "1559bdc7-e836-4b32-9c58-03185d2e0cb2" may be persisted to storage in unencrypted form.
2020-09-16 13:12:19.020 +00:00 [INF] Writing data to file '/root/.aspnet/DataProtection-Keys/key-1559bdc7-e836-4b32-9c58-03185d2e0cb2.xml'.
2020-09-16 13:12:19.588 +00:00 [INF] Now listening on: http://[::]:80
2020-09-16 13:12:19.589 +00:00 [INF] Application started. Press Ctrl+C to shut down.
2020-09-16 13:12:19.589 +00:00 [INF] Hosting environment: Production
2020-09-16 13:12:19.589 +00:00 [INF] Content root path: /app
2020-09-16 13:12:23.208 +00:00 [INF] Request starting HTTP/1.1 GET http://115.29.128.210:9001/ss-admin/login/  
2020-09-16 13:12:23.218 +00:00 [INF] The file /ss-admin/login/index.html was not modified
2020-09-16 13:12:23.221 +00:00 [INF] Request finished in 15.4488ms 304 text/html
2020-09-16 13:12:23.395 +00:00 [INF] Request starting HTTP/1.1 GET http://115.29.128.210:9001/api/admin/login  
2020-09-16 13:12:23.395 +00:00 [INF] Request starting HTTP/1.1 GET http://115.29.128.210:9001/sitefiles/assets/images/favicon.png  
2020-09-16 13:12:23.405 +00:00 [INF] Sending file. Request path: '/sitefiles/assets/images/favicon.png'. Physical path: '/app/wwwroot/sitefiles/assets/images/favicon.png'
2020-09-16 13:12:23.406 +00:00 [INF] Request finished in 10.7842ms 200 image/png
2020-09-16 13:12:23.574 +00:00 [INF] Failed to validate the token.
Microsoft.IdentityModel.Tokens.SecurityTokenInvalidSignatureException: IDX10503: Signature validation failed. Keys tried: '[PII is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
Exceptions caught:
 '[PII is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
token: '[PII is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters, SecurityToken& validatedToken)
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
2020-09-16 13:12:23.585 +00:00 [INF] Bearer was not authenticated. Failure message: IDX10503: Signature validation failed. Keys tried: '[PII is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
Exceptions caught:
 '[PII is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
token: '[PII is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
2020-09-16 13:12:23.587 +00:00 [INF] Executing endpoint 'SSCMS.Web.Controllers.Admin.LoginController.Get (SSCMS.Web)'
2020-09-16 13:12:23.622 +00:00 [INF] Route matched with {action = "Get", controller = "Login"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.ActionResult`1[SSCMS.Web.Controllers.Admin.LoginController+GetResult]] Get() on controller SSCMS.Web.Controllers.Admin.LoginController (SSCMS.Web).
2020-09-16 13:12:23.746 +00:00 [INF] Executing ObjectResult, writing value of type 'SSCMS.Web.Controllers.Admin.LoginController+GetResult'.
2020-09-16 13:12:23.800 +00:00 [INF] Executed action SSCMS.Web.Controllers.Admin.LoginController.Get (SSCMS.Web) in 172.1854ms
2020-09-16 13:12:23.800 +00:00 [INF] Executed endpoint 'SSCMS.Web.Controllers.Admin.LoginController.Get (SSCMS.Web)'
2020-09-16 13:12:23.800 +00:00 [INF] Request finished in 406.0116ms 200 application/json; charset=utf-8
2020-09-16 13:12:23.910 +00:00 [INF] Request starting HTTP/1.1 GET http://115.29.128.210:9001/api/admin/install  
2020-09-16 13:12:23.915 +00:00 [INF] Failed to validate the token.
Microsoft.IdentityModel.Tokens.SecurityTokenInvalidSignatureException: IDX10503: Signature validation failed. Keys tried: '[PII is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
Exceptions caught:
 '[PII is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
token: '[PII is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters, SecurityToken& validatedToken)
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
2020-09-16 13:12:23.916 +00:00 [INF] Bearer was not authenticated. Failure message: IDX10503: Signature validation failed. Keys tried: '[PII is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
Exceptions caught:
 '[PII is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
token: '[PII is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
2020-09-16 13:12:23.916 +00:00 [INF] Executing endpoint 'SSCMS.Web.Controllers.Admin.InstallController.Get (SSCMS.Web)'
2020-09-16 13:12:23.921 +00:00 [INF] Route matched with {action = "Get", controller = "Install"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.ActionResult`1[SSCMS.Web.Controllers.Admin.InstallController+GetResult]] Get() on controller SSCMS.Web.Controllers.Admin.InstallController (SSCMS.Web).
2020-09-16 13:12:23.932 +00:00 [INF] Executing ObjectResult, writing value of type 'SSCMS.Web.Controllers.Admin.InstallController+GetResult'.
2020-09-16 13:12:23.942 +00:00 [INF] Executed action SSCMS.Web.Controllers.Admin.InstallController.Get (SSCMS.Web) in 20.9901ms
2020-09-16 13:12:23.942 +00:00 [INF] Executed endpoint 'SSCMS.Web.Controllers.Admin.InstallController.Get (SSCMS.Web)'
2020-09-16 13:12:23.942 +00:00 [INF] Request finished in 33.0443ms 200 application/json; charset=utf-8
2020-09-16 13:12:46.303 +00:00 [INF] Request starting HTTP/1.1 POST http://115.29.128.210:9001/api/admin/install/actions/databaseConnect application/json;charset=UTF-8 249
2020-09-16 13:12:46.306 +00:00 [INF] CORS policy execution successful.
2020-09-16 13:12:46.310 +00:00 [INF] Failed to validate the token.
Microsoft.IdentityModel.Tokens.SecurityTokenInvalidSignatureException: IDX10503: Signature validation failed. Keys tried: '[PII is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
Exceptions caught:
 '[PII is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
token: '[PII is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters, SecurityToken& validatedToken)
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
2020-09-16 13:12:46.311 +00:00 [INF] Bearer was not authenticated. Failure message: IDX10503: Signature validation failed. Keys tried: '[PII is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
Exceptions caught:
 '[PII is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
token: '[PII is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
2020-09-16 13:12:46.311 +00:00 [INF] Executing endpoint 'SSCMS.Web.Controllers.Admin.InstallController.DatabaseConnect (SSCMS.Web)'
2020-09-16 13:12:46.323 +00:00 [INF] Route matched with {action = "DatabaseConnect", controller = "Install"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.ActionResult`1[SSCMS.Web.Controllers.Admin.InstallController+DatabaseConnectResult]] DatabaseConnect(DatabaseConnectRequest) on controller SSCMS.Web.Controllers.Admin.InstallController (SSCMS.Web).
2020-09-16 13:12:46.732 +00:00 [INF] Executing ObjectResult, writing value of type 'SSCMS.Web.Controllers.Admin.InstallController+DatabaseConnectResult'.
2020-09-16 13:12:46.736 +00:00 [INF] Executed action SSCMS.Web.Controllers.Admin.InstallController.DatabaseConnect (SSCMS.Web) in 412.3687ms
2020-09-16 13:12:46.737 +00:00 [INF] Executed endpoint 'SSCMS.Web.Controllers.Admin.InstallController.DatabaseConnect (SSCMS.Web)'
2020-09-16 13:12:46.737 +00:00 [INF] Request finished in 434.0938ms 200 application/json; charset=utf-8
2020-09-16 13:13:10.192 +00:00 [INF] Request starting HTTP/1.1 POST http://115.29.128.210:9001/api/admin/install/actions/prepare application/json;charset=UTF-8 498
2020-09-16 13:13:10.192 +00:00 [INF] CORS policy execution successful.
2020-09-16 13:13:10.196 +00:00 [INF] Failed to validate the token.
Microsoft.IdentityModel.Tokens.SecurityTokenInvalidSignatureException: IDX10503: Signature validation failed. Keys tried: '[PII is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
Exceptions caught:
 '[PII is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
token: '[PII is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters, SecurityToken& validatedToken)
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
2020-09-16 13:13:10.197 +00:00 [INF] Bearer was not authenticated. Failure message: IDX10503: Signature validation failed. Keys tried: '[PII is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
Exceptions caught:
 '[PII is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
token: '[PII is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
2020-09-16 13:13:10.197 +00:00 [INF] Executing endpoint 'SSCMS.Web.Controllers.Admin.InstallController.Prepare (SSCMS.Web)'
2020-09-16 13:13:10.202 +00:00 [INF] Route matched with {action = "Prepare", controller = "Install"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.ActionResult`1[SSCMS.Dto.StringResult]] Prepare(PrepareRequest) on controller SSCMS.Web.Controllers.Admin.InstallController (SSCMS.Web).
2020-09-16 13:13:10.225 +00:00 [INF] Executing ObjectResult, writing value of type 'SSCMS.Dto.StringResult'.
2020-09-16 13:13:10.227 +00:00 [INF] Executed action SSCMS.Web.Controllers.Admin.InstallController.Prepare (SSCMS.Web) in 23.8237ms
2020-09-16 13:13:10.227 +00:00 [INF] Executed endpoint 'SSCMS.Web.Controllers.Admin.InstallController.Prepare (SSCMS.Web)'
2020-09-16 13:13:10.227 +00:00 [INF] Request finished in 36.0208ms 200 application/json; charset=utf-8
2020-09-16 13:13:12.267 +00:00 [INF] Request starting HTTP/1.1 POST http://115.29.128.210:9001/api/admin/install/actions/install application/json;charset=UTF-8 563
2020-09-16 13:13:12.268 +00:00 [INF] CORS policy execution successful.
2020-09-16 13:13:12.272 +00:00 [INF] Failed to validate the token.
Microsoft.IdentityModel.Tokens.SecurityTokenInvalidSignatureException: IDX10503: Signature validation failed. Keys tried: '[PII is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
Exceptions caught:
 '[PII is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
token: '[PII is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters, SecurityToken& validatedToken)
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
2020-09-16 13:13:12.274 +00:00 [INF] Bearer was not authenticated. Failure message: IDX10503: Signature validation failed. Keys tried: '[PII is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
Exceptions caught:
 '[PII is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
token: '[PII is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
2020-09-16 13:13:12.277 +00:00 [INF] Executing endpoint 'SSCMS.Web.Controllers.Admin.InstallController.Install (SSCMS.Web)'
2020-09-16 13:13:12.288 +00:00 [INF] Route matched with {action = "Install", controller = "Install"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.ActionResult`1[SSCMS.Dto.BoolResult]] Install(InstallRequest) on controller SSCMS.Web.Controllers.Admin.InstallController (SSCMS.Web).
2020-09-16 13:13:12.967 +00:00 [INF] Executing ObjectResult, writing value of type 'SSCMS.Dto.BoolResult'.
2020-09-16 13:13:12.970 +00:00 [INF] Executed action SSCMS.Web.Controllers.Admin.InstallController.Install (SSCMS.Web) in 680.7107ms
2020-09-16 13:13:12.970 +00:00 [INF] Executed endpoint 'SSCMS.Web.Controllers.Admin.InstallController.Install (SSCMS.Web)'
2020-09-16 13:13:12.970 +00:00 [INF] Request finished in 704.5253ms 200 application/json; charset=utf-8
2020-09-16 13:18:49.189 +00:00 [INF] Request starting HTTP/1.1 GET http://115.29.128.210:9001/api/admin/index?siteId=0&sessionId=c98bca7e-fbe3-4747-9415-8d411d655d6d  
2020-09-16 13:18:49.197 +00:00 [INF] Failed to validate the token.
Microsoft.IdentityModel.Tokens.SecurityTokenInvalidSignatureException: IDX10503: Signature validation failed. Keys tried: '[PII is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
Exceptions caught:
 '[PII is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
token: '[PII is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters, SecurityToken& validatedToken)
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
2020-09-16 13:18:49.197 +00:00 [INF] Bearer was not authenticated. Failure message: IDX10503: Signature validation failed. Keys tried: '[PII is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
Exceptions caught:
 '[PII is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
token: '[PII is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
2020-09-16 13:18:49.198 +00:00 [INF] Executing endpoint 'SSCMS.Web.Controllers.Admin.IndexController.Get (SSCMS.Web)'
2020-09-16 13:18:49.205 +00:00 [INF] Route matched with {action = "Get", controller = "Index"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.ActionResult`1[SSCMS.Web.Controllers.Admin.IndexController+GetResult]] Get(GetRequest) on controller SSCMS.Web.Controllers.Admin.IndexController (SSCMS.Web).
2020-09-16 13:18:49.352 +00:00 [INF] Executing HttpStatusCodeResult, setting HTTP status code 401
2020-09-16 13:18:49.352 +00:00 [INF] Executed action SSCMS.Web.Controllers.Admin.IndexController.Get (SSCMS.Web) in 146.6363ms
2020-09-16 13:18:49.352 +00:00 [INF] Executed endpoint 'SSCMS.Web.Controllers.Admin.IndexController.Get (SSCMS.Web)'
2020-09-16 13:18:49.353 +00:00 [INF] Request finished in 163.77ms 401 
2020-09-16 13:18:49.461 +00:00 [INF] Request starting HTTP/1.1 GET http://115.29.128.210:9001/api/admin/login  
2020-09-16 13:18:49.462 +00:00 [INF] Failed to validate the token.
Microsoft.IdentityModel.Tokens.SecurityTokenInvalidSignatureException: IDX10503: Signature validation failed. Keys tried: '[PII is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
Exceptions caught:
 '[PII is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
token: '[PII is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters, SecurityToken& validatedToken)
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
2020-09-16 13:18:49.463 +00:00 [INF] Bearer was not authenticated. Failure message: IDX10503: Signature validation failed. Keys tried: '[PII is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
Exceptions caught:
 '[PII is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
token: '[PII is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
2020-09-16 13:18:49.464 +00:00 [INF] Executing endpoint 'SSCMS.Web.Controllers.Admin.LoginController.Get (SSCMS.Web)'
2020-09-16 13:18:49.464 +00:00 [INF] Route matched with {action = "Get", controller = "Login"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.ActionResult`1[SSCMS.Web.Controllers.Admin.LoginController+GetResult]] Get() on controller SSCMS.Web.Controllers.Admin.LoginController (SSCMS.Web).
2020-09-16 13:18:49.531 +00:00 [INF] Executing ObjectResult, writing value of type 'SSCMS.Web.Controllers.Admin.LoginController+GetResult'.
2020-09-16 13:18:49.532 +00:00 [INF] Executed action SSCMS.Web.Controllers.Admin.LoginController.Get (SSCMS.Web) in 67.238ms
2020-09-16 13:18:49.532 +00:00 [INF] Executed endpoint 'SSCMS.Web.Controllers.Admin.LoginController.Get (SSCMS.Web)'
2020-09-16 13:18:49.532 +00:00 [INF] Request finished in 71.0363ms 200 application/json; charset=utf-8
2020-09-16 13:18:49.556 +00:00 [INF] Request starting HTTP/1.1 POST http://115.29.128.210:9001/api/admin/login/captcha  0
2020-09-16 13:18:49.556 +00:00 [INF] CORS policy execution successful.
2020-09-16 13:18:49.557 +00:00 [INF] Failed to validate the token.
Microsoft.IdentityModel.Tokens.SecurityTokenInvalidSignatureException: IDX10503: Signature validation failed. Keys tried: '[PII is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
Exceptions caught:
 '[PII is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
token: '[PII is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters, SecurityToken& validatedToken)
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
2020-09-16 13:18:49.557 +00:00 [INF] Bearer was not authenticated. Failure message: IDX10503: Signature validation failed. Keys tried: '[PII is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
Exceptions caught:
 '[PII is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
token: '[PII is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
2020-09-16 13:18:49.557 +00:00 [INF] Executing endpoint 'SSCMS.Web.Controllers.Admin.LoginController.New (SSCMS.Web)'
2020-09-16 13:18:49.559 +00:00 [INF] Route matched with {action = "New", controller = "Login"}. Executing controller action with signature SSCMS.Dto.StringResult New() on controller SSCMS.Web.Controllers.Admin.LoginController (SSCMS.Web).
2020-09-16 13:18:49.650 +00:00 [INF] Executing ObjectResult, writing value of type 'SSCMS.Dto.StringResult'.
2020-09-16 13:18:49.650 +00:00 [INF] Executed action SSCMS.Web.Controllers.Admin.LoginController.New (SSCMS.Web) in 90.894ms

**Comment by Eric-zsp** [comment]
已解决，mysql服务器未开启autocommit
