### ISSUE TITLE
无法编译

### ISSUE THREAD

**Issue by zhongshuiyuan** [siteserver/cms#2608]
运行npm run build-win-x64时报如下错误
TypeError: content.matchAll(...) is not a function or its return value is not iterable
    at transform (F:\JointCode\NetCore\siteserver-cms\gulpfile.js:30:29)
    at DestroyableTransform.gulp.src.pipe.through2.obj [as _transform] (F:\JointCode\NetCore\siteserver-cms\gulpfile.js:84:16)
    at DestroyableTransform.Transform._read (F:\JointCode\NetCore\siteserver-cms\node_modules\readable-stream\lib\_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (F:\JointCode\NetCore\siteserver-cms\node_modules\readable-stream\lib\_stream_transform.js:172:83)
    at doWrite (F:\JointCode\NetCore\siteserver-cms\node_modules\readable-stream\lib\_stream_writable.js:428:64)
    at writeOrBuffer (F:\JointCode\NetCore\siteserver-cms\node_modules\readable-stream\lib\_stream_writable.js:417:5)
    at DestroyableTransform.Writable.write (F:\JointCode\NetCore\siteserver-cms\node_modules\readable-stream\lib\_stream_writable.js:334:11)
    at DestroyableTransform.ondata (F:\JointCode\NetCore\siteserver-cms\node_modules\readable-stream\lib\_stream_readable.js:619:20)
    at DestroyableTransform.emit (events.js:198:13)
    at DestroyableTransform.EventEmitter.emit (domain.js:466:23)

**Comment by starlying** [comment]
有可能是NodeJS版本太低导致的

**Comment by zhongshuiyuan** [comment]
好的，我升级下版本试试
